WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:75 短信验证码为：185499
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:75 短信验证码为：670542
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:75 短信验证码为：723170
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:75 短信验证码为：837183
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:76 短信验证码为：213612
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:76 短信验证码为：009683
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:76 短信验证码为：250692
WARNING _internal.py:88  * Debugger is active!
DEBUG verify.py:76 短信验证码为：829875
DEBUG verify.py:76 短信验证码为：326120
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR profile.py:29 'BaseQuery' object has no attribute 'frist'
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR profile.py:66 'BaseQuery' object has no attribute 'frist'
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR profile.py:96 (_mysql_exceptions.OperationalError) (1048, "Column 'name' cannot be null") [SQL: u'UPDATE ih_user_profile SET update_time=%s, name=%s WHERE ih_user_profile.id = %s'] [parameters: (datetime.datetime(2018, 4, 7, 17, 19, 12, 905595), None, 1L)] (Background on this error at: http://sqlalche.me/e/e3q8)
WARNING _internal.py:88  * Debugger is active!
ERROR profile.py:96 (_mysql_exceptions.OperationalError) (1048, "Column 'name' cannot be null") [SQL: u'UPDATE ih_user_profile SET update_time=%s, name=%s WHERE ih_user_profile.id = %s'] [parameters: (datetime.datetime(2018, 4, 7, 17, 27, 53, 382219), None, 1L)] (Background on this error at: http://sqlalche.me/e/e3q8)
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR profile.py:29 get() got an unexpected keyword argument 'id'
ERROR profile.py:29 get() got an unexpected keyword argument 'id'
WARNING _internal.py:88  * Debugger is active!
ERROR profile.py:30 get() got an unexpected keyword argument 'id'
WARNING _internal.py:88  * Debugger is active!
ERROR profile.py:31 get() got an unexpected keyword argument 'id'
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR passport.py:34 get() got an unexpected keyword argument 'id'
WARNING _internal.py:88  * Debugger is active!
ERROR passport.py:34 filter() got an unexpected keyword argument 'mobile'
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR _internal.py:88 Error on request:
Traceback (most recent call last):
  File "/home/zhuolin/.virtualenvs/py2_Flask/lib/python2.7/site-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/home/zhuolin/.virtualenvs/py2_Flask/lib/python2.7/site-packages/werkzeug/serving.py", line 263, in execute
    write(b'')
  File "/home/zhuolin/.virtualenvs/py2_Flask/lib/python2.7/site-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
ERROR house.py:128 object of type 'NoneType' has no len()
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
WARNING _internal.py:88  * Debugger is active!
